# Generated by Django 3.2.13 on 2022-07-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальность'},
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='url',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.city', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='url',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.language', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.city', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.language', verbose_name='Специальность'),
        ),
    ]
